exports.lang = {
    siteName: 'Shiny',
    home: '首頁',
    ShinyChang: 'Shiny Chang',
    lastUpdate: '最後更新',
    createTime: '建立時間',
    author: '作者',
    title: '標題',
    articleList: '文章列表',
    personalExperience: '個人經歷',
    olderArticle: '較舊的文章',
    newerArticle: '較新的文章',
    articleNotFound: '沒有找到文章',
    goHome: '回首頁',
    save: '儲存',
    signIn: '登入',
    about: '關於',
    article: '文章',
    archive: '所有文章',
    logout: '登出',
    backToTop: '回到最上面',
    tagList: '標籤列表',
    recentArticle: '最新文章',
    playground: '遊樂園',
    portfolio: '作品集',
    readmore: '閱讀更多...'
}
